=== sweeetsense/sweeety/web1/WebContent/xml_ex/abc.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT jikwons (jikwon*)>
	<!ELEMENT jikwon (irum, (jik|gender), pay?)>
		<!ELEMENT irum (#PCDATA)>
		<!ELEMENT jik (#PCDATA)>
		<!ELEMENT gender (#PCDATA)>
		<!ELEMENT pay (#PCDATA)>

=== sweeetsense/sweeety/web1/WebContent/xml_ex/ex3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jikwons SYSTEM "abc.dtd" >
<jikwons>
	<jikwon>
		<irum>동철</irum>
		<gender>남</gender>
		<pay>6700</pay>
	</jikwon>
	<jikwon>
		<irum>현진</irum>
		<gender>부장</gender>
	</jikwon>
</jikwons>
